export const projectKnowledge = {
 purpose:'Calgary road inspection decision support: reactive historical priorities and proactive report outlooks. Not verified crash risk or autonomous action.',
 workflows:{historical:'Applied evidence scope, Top20 ranking, report evidence, weather associations, comparison, playback and export.',weekly:'7-day Ridge Poisson in browser worker; equal pooled temporal features or experimental learned event-type features; all-report or collision-related target.',monthly:'Precomputed pure EB; fixed 3-year history; full road/intersection inventory; six replay cutoffs and latest complete-day future prediction; site controls, CMF review candidates and saved local inspection reviews.',annual:'Precomputed EB; latest future and monthly historical replay cutoffs; fixed 5-year replay history; source evidence, predictive intervals, ridge/simple baselines. Partial observations are not full annual evaluation.'},
 units:'Reactive/weekly locations are observed nearest-road/grid groups. Monthly/annual use full inventory of 120567 segments and 46007 derived intersections. IDs/populations are not interchangeable; cross-unit shortlist overlap is invalid.',
 algorithms:'Historical ranking combines frequency, growth and recurrence. Learned historical type weights adapt positive collision-model coefficients only to frequency and remain unvalidated. EB blends SPF site-characteristic expectation and own history; NB posterior gives 90% predictive intervals. Poisson CV uses 2023→2024 and 2023–24→2025; outcomes do not choose parameters in 2026.',
 sources:['City Calgary Traffic Incidents official archive (UTC timestamps; America/Edmonton display)','City Street Centreline current geometry','City Traffic Volumes 2016–19 and 2022–24 for EB; 2024 context in reactive data','City Traffic Signals, Stop/Yield Traffic Signs, Crosswalks','ECCC CALGARY INTL A hourly airport weather; fixed UTC−7 source LST conversion','OpenFreeMap/OpenMapTiles/OpenStreetMap basemap','FHWA CMF Clearinghouse external crash-treatment studies','industry-hackathon-lab starter: original 2025 snapshot differs from later official retrieval/time conventions'],
 limitations:['Traffic reports include stalls and signals; text categories are not verified severity.','Current geometry, ambiguous junction proximity, undated assets and unknown removals limit historical validity.','Traffic volume release-time availability unverified; weather is one airport station, not road surface.','CMFs cannot be multiplied by all-report forecasts to estimate avoided crashes/reports.','Inspected 2026 comparisons are exploratory; some windows lose. No validated business or safety benefit.','Reviews are explicitly saved locally and shared through export; checklist checks are reviewer feedback.'],
 navigation:'Map preview: playback/fullscreen; Evidence: source review; Plan comparison: saved plan differences; Historical evaluation: retrospective experiments; Forward outlook: 7/30/365-day modes; Weather context: associations; Data & method: provenance; Agent: evidence conversation and historical plan evaluation tools. Plan evaluation searches 21 weight combinations on six 2023–2025 windows and checks a frozen July 2026 holdout. Use supplied planEvaluation numbers; do not fabricate results or claim safety improvements.'
};
